#!/bin/sh

set -e

OWD=$PWD
TMP=tmp/scte
DIR=$PWD/new/scte


rm -fr $TMP $DIR
mkdir -p $TMP $DIR

cd $TMP

curl -sS 'https://www.scte.org/standards/library/catalog/?index_search_query=mib' | \
    grep href | \
    grep -E -- -mib\|management-information-base | \
    grep -Ev framework\|requirement | \
    while read url; do
	furl=$(echo $url | sed s/href=//)
	murl=$(curl -sS https://www.scte.org$furl | grep href= | grep -E '\.mib|\.txt' | sed s/href=//)
	curl -LOsS $murl || echo $url
    done

cp -p * $DIR

patch -d $DIR <$OWD/scte.patch
