#!/bin/sh

TMP=tmp/ieee
DIR=$PWD/new/ieee

rm -fr $TMP
mkdir -p $TMP
( cd $TMP
  wget -r -A .mib -np -nd -nv http://www.ieee802.org/1/files/public/MIBs/
  rm -f 802*
)

rm -fr $DIR
mkdir -p $DIR
for f in $TMP/*
do
    g=$(echo $f | sed -e 's/-[0-9Z]*.mib/.txt/' -e s%$TMP/%%)
    sed -e 's/\r//' $f | awk '{if(NR==1)sub(/^[\xef\xbb\xbf]*/,"");print}' >$DIR/$g
done

# patch -d $DIR <ieee.diff
