#!/bin/sh

set -e

TMPDIR=tmp
NEWDIR=new

TMPGIT=$TMPDIR/cisco-mibs
TMPDL=$TMPDIR/cisco-mibs/v2
if [ ! -d $TMPGIT ]; then
    mkdir -p $TMPDIR
    cd $TMPDIR
    git clone git@github.com:cisco/cisco-mibs.git
    cd ..
fi

cd $TMPGIT
git pull
cd ../..

rm -fr $NEWDIR/cisco $NEWDIR/cisco-fp $NEWDIR/cisco-lwapp $NEWDIR/cisco-ucs $NEWDIR/altiga $NEWDIR/docsis $NEWDIR/lanoptics $NEWDIR/clab
mkdir -p $NEWDIR

rm -fr $TMPDIR/non-cisco
mkdir -p $TMPDIR/non-cisco
cp -p $TMPDL/* $TMPDIR/non-cisco
rm $TMPDIR/non-cisco/CISCO*

mkdir $NEWDIR/cisco $NEWDIR/cisco-fp $NEWDIR/cisco-lwapp $NEWDIR/cisco-ucs
cp -p $TMPDL/CISCO* $NEWDIR/cisco
rm $NEWDIR/cisco/*CAPABILITY*
mv $NEWDIR/cisco/CISCO-FIREPOWER* $NEWDIR/cisco-fp
mv $NEWDIR/cisco/CISCO-LWAPP* $NEWDIR/cisco-lwapp
mv $TMPDIR/non-cisco/AIRESPACE* $NEWDIR/cisco-lwapp
mv $NEWDIR/cisco/CISCO-UNIFIED-COMPUTING* $NEWDIR/cisco-ucs
for m in BASIS-GENERIC-MIB.my \
    BASIS-MIB.my \
    BASIS-ONLINE-DIAG-MIB.my \
    BASIS-RAS-DISK-MIB.my \
    BASIS-SERIAL-MIB.my \
    BASIS-SHELF-MIB.my \
    GENERICOBJECT-MIB.my \
    IGMP-MIB.my \
    INT-SERV-MIB.my \
    MPLS-VPN-MIB.my \
    RPHY-NDF-NDR-MIB.my \
    RTM-MIB.my \
    OLD-CISCO-CHASSIS-MIB.my
do mv $TMPDIR/non-cisco/$m $NEWDIR/cisco
done
mv $TMPDIR/non-cisco/NAT-MIB.my $NEWDIR/cisco/XXX-NAT-MIB.my

patch -d $NEWDIR/cisco <cisco.diff
patch -d $NEWDIR/cisco-lwapp <cisco-lwapp.diff

mkdir $NEWDIR/altiga
mv $TMPDIR/non-cisco/ALTIGA* $TMPDIR/non-cisco/ADMIN-AUTH-STATS-MIB.my $NEWDIR/altiga

mkdir $NEWDIR/docsis
mv $TMPDIR/non-cisco/DOCS-* $NEWDIR/docsis
rm $NEWDIR/docsis/DOCS-IETF* $NEWDIR/docsis/DOCS-BPI-MIB.my $NEWDIR/docsis/DOCS-IF-MIB.my $NEWDIR/docsis/DOCS-CABLE-DEVICE-MIB.my

patch -d $NEWDIR/docsis <docsis.diff

mkdir $NEWDIR/lanoptics
mv $TMPDIR/non-cisco/LANOPT* $NEWDIR/lanoptics

mkdir $NEWDIR/clab
mv $TMPDIR/non-cisco/CLAB* $TMPDIR/non-cisco/DTI-MIB.my $TMPDIR/non-cisco/DSG-IF-MIB.my $NEWDIR/clab
