#!/bin/sh

TMP=$PWD/tmp/clab
DIR=$PWD/new/clab

rm -fr $TMP
mkdir -p $TMP
cd $TMP
wget -r -A .txt -np -nd -nv -l 1 http://mibs.cablelabs.com/MIBs/common

rm -fr $DIR
mkdir -p $DIR
for f in *
do
    g=$(echo $f | sed 's/-[0-9Z]*.txt/.txt/')
    sed -e 's/\r//' $f | awk '{if(NR==1)sub(/^[\xef\xbb\xbf]*/,"");print}' >$DIR/$g
done
